name: Generate GitBlog README

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - main
    paths:
      - main.py

env:
  GITHUB_NAME: ISheepp
  GITHUB_EMAIL: lzyoutlook@gmail.com

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate new md # if you fork or clone this repo, please delete the curl line unless you know why
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'
       # Fix for the unsafe repo error: https://github.com/repo-sync/pull-request/issues/84
      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push README
        run: |
          git config --local user.name ISheep
          git config --local user.email lzyoutlook@gmail.com
          git add .
          git commit -m "generated readme" || echo "no need to commit "
          git push || echo "no file change"
